### ISSUE TITLE
楼主utils.py这个工具类可以用faker代替

### ISSUE THREAD

**Issue by qq771026828** [jinwu18/web-app-h5-api-pyTestAutomation#1]
楼主utils.py这个工具类可以用faker代替

![123](https://user-images.githubusercontent.com/21036501/180974863-50ac7991-e441-407c-a808-3d48dbb99a39.png)
-

**Comment by qq771026828** [comment]
![Uploading image.png…]()

**Comment by jinwu18** [comment]
是的，多谢，faker这个对造数据很有帮助
